2024-02-12 15:54:40,364 ERROR: Exception on /edit_profile [POST] [in /home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/stijn/flaskproject/app/routes.py", line 87, in edit_profile
    db.session.commit()
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 598, in commit
    return self._proxied.commit()
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1969, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4447, in _flush
    with util.safe_reraise():
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 910, in _emit_update_statements
    c = connection.execute(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('susan', '', 2)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-02-12 15:55:48,015 INFO: Flaskproject startup [in /home/stijn/flaskproject/app/__init__.py:41]
2024-02-12 15:55:55,192 ERROR: Exception on /edit_profile [POST] [in /home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/stijn/flaskproject/app/routes.py", line 84, in edit_profile
    if form.validate_on_submit():
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/wtforms/form.py", line 329, in validate
    return super().validate(extra)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/wtforms/form.py", line 146, in validate
    if not field.validate(self, extra):
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/wtforms/fields/core.py", line 246, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/wtforms/fields/core.py", line 266, in _run_validation_chain
    validator(form, self)
  File "/home/stijn/flaskproject/app/forms.py", line 44, in validate_username
    user = db.session.scalar(sa.select(User).where(User.username) == self.username.data)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 1859, in scalar
    return self._proxied.scalar(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2358, in scalar
    return self._execute_internal(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2088, in _execute_internal
    statement = coercions.expect(roles.StatementRole, statement)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 413, in expect
    resolved = impl._literal_coercion(
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 651, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "/home/stijn/flaskproject/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 535, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: Executable SQL or text() construct expected, got False.
2024-02-12 15:57:45,360 INFO: Flaskproject startup [in /home/stijn/flaskproject/app/__init__.py:41]
2024-02-12 18:58:24,859 INFO: Flaskproject startup [in /home/stijn/flaskproject/app/__init__.py:41]
2024-02-12 19:04:34,360 INFO: Flaskproject startup [in /home/stijn/flaskproject/app/__init__.py:41]
2024-02-12 19:04:46,746 INFO: Flaskproject startup [in /home/stijn/flaskproject/app/__init__.py:41]
2024-02-12 19:04:55,561 INFO: Flaskproject startup [in /home/stijn/flaskproject/app/__init__.py:41]
2024-02-24 15:34:45,040 INFO: Flaskproject startup [in /home/stijn/repos/flaskproject/app/__init__.py:52]
2024-03-13 21:38:05,715 INFO: Flaskproject startup [in /home/stijn/repos/flaskproject/app/__init__.py:98]
2024-03-13 21:38:05,715 INFO: Flaskproject startup [in /home/stijn/repos/flaskproject/app/__init__.py:120]
2024-03-13 21:38:05,715 INFO Flaskproject startup [in /home/stijn/repos/flaskproject/app/__init__.py:120]
2024-03-16 17:27:34,685 INFO: Flaskproject startup [in /home/stijn/repos/flaskproject/app/__init__.py:104]
2024-03-16 17:28:03,891 INFO: Flaskproject startup [in /home/stijn/repos/flaskproject/app/__init__.py:104]
